# Build settings
gems:
  - jemoji
  - jekyll-paginate

url: "https://anopows.github.io" # the base hostname & protocol for your site
baseurl: "/Andi-sh-Blog"

# Site settings
title: "Andi.sh Blog"
description: > # this means to ignore newlines until "email:"
   My personal blog about CS and other stuff. 

email: anopows@gmail.com
#blog logo
logo: {{ "/assets/images/df_logo.jpg" | relative_url }}
float_logo: true # true, false (default)

# blog cover
cover: {{ "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg" | relative_url }}

name: 'Andi.sh Blog'
author: 'Andi Bl√∂chliger'
author_image: {{ "/assets/images/author.jpg" | relative_url}}

paginate:	10

#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
# social:
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/anopows
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
